### ISSUE TITLE
Create pretty page for Kyiv chapter.

### ISSUE THREAD

**Issue by sudodoki** [nodeschool/kyiv#1]
I think it might serve the need of informing Ukrainians about our activity & events..

**Comment by sudodoki** [comment]
Have seen @MashaTimmpa do some progress on this.

**Comment by sudodoki** [comment]
There's actually private repo that has new styles, but it's statis and all js is done via clojurescript.

**Comment by zonzujiro** [comment]
Sign me in :) 

Clojurescript globally is ok, but developing can take some additional time because I don't have a lot of experience with it.

**Comment by suchov** [comment]
https://nodeschool.io/kyiv/ Closing this for now.
