### ISSUE TITLE
announce new event

### ISSUE THREAD

**Issue by suchov** [nodeschool/kyiv#11]
We have a pretty site now, we can announce a new event and start preparing to it.

**Comment by suchov** [comment]
@AMashoshyna @zonzujiro what do you think about it?

**Comment by zonzujiro** [comment]
Yeap. I'm in.

**Comment by suchov** [comment]
As a mentor - definitely. I suggest to plan in on the first weekends of November.

**Comment by mykytasamokish** [comment]
Let’s discuss it in private :-)

**Comment by zonzujiro** [comment]
The first event planned on 4th of November.

**Comment by suchov** [comment]
@zonzujiro @AMashoshyna let's maybe post about the first event on AIN? I suggest creating the article by the same link https://goo.gl/V2r8gn ?
