### ISSUE TITLE
Mentor Registration for November 04th, 2017

### ISSUE THREAD

**Issue by zonzujiro** [nodeschool/kyiv#17]
Cogniance is hosting us on November 04th from 12pm. 
The address is: [(2I build.), Okhtyrskyi Ln, 7](https://www.google.com.ua/maps/place/Cogniance/@50.3963984,30.4754383,17z/data=!3m1!4b1!4m5!3m4!1s0x40d4c8d84fa7628f:0x13cad83c9e96a625!8m2!3d50.396395!4d30.477627?hl=en)

This is the first event, so it would be great if mentors:

- Have already completed the core NodeSchool [workshoppers](https://nodeschool.io/#workshopper-list) before the event.
    - Having also completed elective [workshoppers](https://nodeschool.io/#workshopper-list) is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (11:30am) so we can get setup and have our mentor meeting

Confirmed mentors:

- [x] @mykytasamokish
- [x] @ceoworks 
- [x] @bohdan-chechin 
- [x] @demeshko 
- [x] @Veligura 
- [ ] You?

Organizers:
@suchov 
@zonzujiro
@AMashoshyna

Attendee registration link:
https://docs.google.com/forms/d/e/1FAIpQLSeT83iELIoxweFeRuZ8jc4x1dTmfWY4y8hiJHx7M-CTA9esFw/viewform

Leave comments on this issue if you want to be a mentor.

**Comment by ceoworks** [comment]
hello, I could be a mentor for 3 hours at this event

**Comment by zonzujiro** [comment]
Great, thanks!

**Comment by bohdan-chechin** [comment]
@zonzujiro hey, i'd like to join mentors team

**Comment by zonzujiro** [comment]
@bohdan-chechin Great, thanks! Fill free to contact me, if you will have some questions.

**Comment by demeshko** [comment]
i'm in! you can count on me on Saturdays

**Comment by zonzujiro** [comment]
@demeshko got it! Thank you

**Comment by Veligura** [comment]
I want would be mentor, too)

**Comment by zonzujiro** [comment]
@Veligura welcome on board :) Thank you!
