### ISSUE TITLE
Mentor Registration for April 14th

### ISSUE THREAD

**Issue by suchov** [nodeschool/kyiv#22]
Star is hosting us on April 14 from 12pm. 
The address is: [(2I build.), Okhtyrskyi Ln, 7](https://www.google.com.ua/maps/place/Cogniance/@50.3963984,30.4754383,17z/data=!3m1!4b1!4m5!3m4!1s0x40d4c8d84fa7628f:0x13cad83c9e96a625!8m2!3d50.396395!4d30.477627?hl=en)

It would be great if mentors:

- Have already completed the core NodeSchool [workshoppers](https://nodeschool.io/#workshopper-list) before the event.
    - Having also completed elective [workshoppers](https://nodeschool.io/#workshopper-list) is a great bonus.
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Arrive 30 minutes early (11:30am) so we can get set up and have our mentor meeting

Confirmed mentors:
- [x] @denysdovhan
- [x] @zonzujiro
- [x] @itspoma 
- [ ] You?

Organizers:
@suchov 
@AMashoshyna

Leave comments on this issue if you want to be a mentor.

**Comment by itspoma** [comment]
+

**Comment by denysdovhan** [comment]
I’d like to join your team. I’ve completed all of the core workshoppers. I’m actually an author of two of them. I have experience in organizing NodeSchool Chernivtsi.

**Comment by AMashoshyna** [comment]
@denysdovhan awesome!

**Comment by suchov** [comment]
Let me add you to the list @denysdovhan

**Comment by suchov** [comment]
> I’d like to join your team. I’ve completed all of the core workshoppers. I’m actually an author of two of them. I have experience in organizing NodeSchool Chernivtsi.

![image](https://user-images.githubusercontent.com/1478985/55391505-2ba5cf00-5542-11e9-9d91-91af0f0bd57c.png)

**Comment by suchov** [comment]
At the end of the day, it was fun and teaching, let's repeat.
