### ISSUE TITLE
Please, write "Kyiv", not "Kiev"

### ISSUE THREAD

**Issue by denysdovhan** [nodeschool/kyiv#23]
Your twitter account has been named incorrectly. Please, write Kyiv, not Kiev.

<img width="447" alt="Screen Shot 2019-03-21 at 14 19 50" src="https://user-images.githubusercontent.com/3459374/54751722-7ccdce80-4be4-11e9-8cd7-006cc8d72f3c.png">

**Comment by suchov** [comment]
"Украина" It's your configs @denysdovhan

**Comment by suchov** [comment]
The rest is done.

**Comment by denysdovhan** [comment]
Yay 🎉
