### ISSUE TITLE
add our event to nodeschool.io

### ISSUE THREAD

**Issue by suchov** [nodeschool/kyiv#24]
we need to add our event to the list of all events!

**Comment by sudodoki** [comment]
Responses
![image](https://user-images.githubusercontent.com/1506905/55035811-937b8780-5021-11e9-9710-acfbc042380c.png)

It's live
![image](https://user-images.githubusercontent.com/1506905/55035905-c756ad00-5021-11e9-88c2-de4ec3f81177.png)

**Comment by suchov** [comment]
thanks @sudodoki
