### ISSUE TITLE
Create hex sticker

### ISSUE THREAD

**Issue by sudodoki** [nodeschool/kyiv#5]
Would be super cool to have sticker, like other chapters do. [See existing](http://nodeschool.io/hexdex.html). Template is [here](https://github.com/nodeschool/nodeschool.github.io/tree/master/images/make-a-sticker).

**Comment by MashaTimmpa** [comment]
let me suggest my variant
![nodeschool-kbp](https://cloud.githubusercontent.com/assets/9108856/6084381/a0a7812e-ae41-11e4-98ea-e700540c9e66.png)

**Comment by MashaTimmpa** [comment]
Would like to suggest my variant:
![nodeschool-kbp-sm](https://cloud.githubusercontent.com/assets/9108856/6084431/15f67b4c-ae42-11e4-924f-b8287fafe3ee.png)

**Comment by sudodoki** [comment]
:+1: LGTM. @nodeschool/kyiv do you have any edits/suggestions? Otherwise might as well go on and print out a bunch of these.

**Comment by sejoker** [comment]
Nice, what KBP means?

**Comment by sudodoki** [comment]
@sejoker it's Boryspil international airport 3 letter abbreviation. I don't have a link but that's what supposed to go on the sticker. Not sure, might want @jlord to confrim.

**Comment by jlord** [comment]
I think whatever letters the city commonly uses should go there (so it's then easily recognizable to people there). For a lot of places that's the airport code but it doesn't _have_ to be. 

This sticker is :sparkle: :green_heart:

**Comment by MashaTimmpa** [comment]
Cool, that u liked it, guys!

Changed KBP -> KYIV 

Is it ok with color? On my laptop green color is rather leaf-like, but on mobile device green looks a bit neon.
![nodeschool-kyiv-2-sm](https://cloud.githubusercontent.com/assets/9108856/6091356/6a6997fa-aeb9-11e4-8f45-5ff981997363.png)

**Comment by sejoker** [comment]
The color looks naturally green on my mobile. It's cool

**Comment by sudodoki** [comment]
@MashaTimmpa If you want 4 letters, you might wanna take a look at http://nodeschool.io/images/nodeschool-hradec-kralove.svg or http://nodeschool.io/images/nodeschool-bali-sticker.png.

**Comment by MashaTimmpa** [comment]
New variant of Kyiv sign
![nodeschool-kyiv-5-sm](https://cloud.githubusercontent.com/assets/9108856/6097742/c91a0264-afd9-11e4-9530-85abc4ec1fd7.png)

**Comment by programulya** [comment]
Nice!

**Comment by listochkin** [comment]
what does this gate in front represent? Maybe we should try to style it like our Golden Gate in Kiev?

**Comment by MashaTimmpa** [comment]
The point is that the roof is some reference to varenik, the columns are decorated with stylized fancywork and the door is inspired by the Golden Gate.I'll play with form of school.

**Comment by SleepWalker** [comment]
Here is another one from my girlfriend :)

![nodeschool-kyiv](https://cloud.githubusercontent.com/assets/2536916/6227613/c87404c2-b6aa-11e4-938c-0616fd644afd.png)

**Comment by finnp** [comment]
@SleepWalker Wow this is awesome :) I hope you are adding it to the [Hexdex](http://nodeschool.io/hexdex.html) if it is chosen

**Comment by ghaiklor** [comment]
@SleepWalker nice sticker :+1: 
+ for @SleepWalker 's sticker.

**Comment by SleepWalker** [comment]
May be this one? Or it should be much more green/bright/dark?

![nodeschool-kyiv](https://cloud.githubusercontent.com/assets/2536916/6244111/6aac9612-b757-11e4-9495-894da57067c8.png)

BTW as I know this would be printed. So retina display is not a priority :) (but it doesn't mean that the first colour is better than the current one, of course)

**Comment by jlord** [comment]
@SleepWalker ahhh it's :sparkles: I love it. I like the earlier more muted green more myself, but both are great.

**Comment by jlord** [comment]
Is it green [because](http://en.wikipedia.org/wiki/Kiev)

> Kiev is known as a green city with two botanical gardens and numerous large and small parks.

Cause that's cool!

**Comment by sudodoki** [comment]
I still think letters should be KBP or KYIV. @SleepWalker can we arrange for that?

**Comment by SleepWalker** [comment]
@sudodoki, I thought that KBP (and IEV) is abbreviation of an airport. Is it also abbreviation of Kiev?

The three letters was chosen, to follow the style of nodeschool stickers. It can be drawn with four letters, but it will be not so neat. So we should choose between clarity and appearance :)

And one more thing: Kiev or Kyiv? As for me Kiev is more common. I think for native English speakers too: we have wiki for [Kiev](http://en.wikipedia.org/wiki/Kiev), where Kyiv is an alias.

**Comment by SleepWalker** [comment]
Sorry, I've forgot that the KBP was discussed earlier... But nevertheless I think, that airport abbreviations isn't the best option.

**Comment by sudodoki** [comment]
@SleepWalker try googling `KBP` & `KYI` & `KIE`. :trollface:

**Comment by MashaTimmpa** [comment]
@SleepWalker I had the same argue about KBP or KYIV with @sudodoki earlier in this thread, so totaly understand you (handshake). As for spelling our city's name -  it's Kyiv.Love in your variants the play with leaves - very smart place and size

But I can't see Kyiv in that building, it doesn't  represent Kyiv spirit for me. I always though it might be a lot of nice and fun details on a sticker to make people stare on it during conferences and make questions about it =) And here there is not much about our city.

**Comment by listochkin** [comment]
@MashaTimmpa agree, I do not recognise buildings on both stickers actually.

**Comment by MashaTimmpa** [comment]
@listochkin got me :D On my sticker there is reference for Lavra standing on hills, the front building is just a building with a varenik-roof, such a common picture of ukrainian futuristic school (as I understood the primary whole idea of nodeschool sticker)

**Comment by SleepWalker** [comment]
@sudodoki when I google for KBP and IEV I get two airports (and of coarse Knowledge Based Processor :) ). KYI — nothing.

@MashaTimmpa one more :+1: for kiev is the fact that we have domain `kiev.ua` and not `kyiv.ua`.

So I vote for Kiev or Kyiv, when no one wants Kiev  :)

**Comment by MashaTimmpa** [comment]
@SleepWalker there can be no voting - official spelling of Ukrainian capital is Kyiv, here is url on Ministry of Foreign Affairs of Ukraine http://mfa.gov.ua/en/about-ukraine/info/general-facts.

**Comment by sudodoki** [comment]
@SleepWalker I'm strongly for Kyiv - Київ.
Can we have 3 letters to be KBP/IEV or have 4 letter for whole city name? Postponing printing until then. :smile_cat:

**Comment by SleepWalker** [comment]
![nodeschool-kyiv](https://cloud.githubusercontent.com/assets/2536916/6437268/fa93e7e6-c0c4-11e4-810b-8eff6d1d9407.png)

**Comment by sudodoki** [comment]
@SleepWalker :bow:

**Comment by suchov** [comment]
:open_mouth:
