### ISSUE TITLE
Looking for someone to take over Kyiv chapter

### ISSUE THREAD

**Issue by sudodoki** [nodeschool/kyiv#6]
Okay, this chapter was kind of failure: 
being created in 2014, it has 1 official event and few times we passed few workshoppers on [kottans](github.com/kottans) weekend workshops.
There was a slowly pacing effort of creating new fancy site and engaging new instructors to run couple more events, but generally I'm moving away from nodeschool, stopping answering questions in nodeschool/discussion a year or even more ago and gradually shifting my time and attention to something else.
So, **is there anyone in Kyiv I know or who has some experience organizing stuff that would like to take over Kyiv chapter?** I'm gonna transfer everything I have in terms of styles for new page / stickers / source files for assets / some leftover laces and badges from first event, etc.
Also, thanks to everyone who made that first event possible and helped us with other things afterwards.

**Comment by suchov** [comment]
I'll take over this with Kottans. Have experience in event planning... Need some help from you to order the stickers, cause it could take some time to deliver them as I know.

**Comment by suchov** [comment]
Closing this too, we'll announce new event pretty soon.
